version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    network_mode: host
  smart-vehicle:
    network_mode: host
    build:
      context: ./smart-vehicle
    depends_on:
      - server
    ports:
      - "5001:5001"